name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          - erlang:26.0
          - erlang:27.0
          - elixir:1.16.0
          - elixir:1.17.0
          - elixir:1.17.2

    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout all history for all branches and tags
        fetch-depth: 0
    - name: Install rebar3 and hex
      if:   ${{ contains(matrix.container, 'elixir') }}
      run:  |
        mix local.rebar --force
        mix local.hex   --force
    - name: Compile
      run:  |
        [ ${{ contains(matrix.container, 'elixir') }} = true ] && export MIX_ENV=test
        make deps
        make compile
    - name: Run tests
      run:  |
        [ ${{ contains(matrix.container, 'elixir') }} = true ] && export MIX_ENV=test
        make benchmark
